### ISSUE TITLE
The test did not run because Enzyme and the Adapter were not imported in index-test.js

### ISSUE THREAD

**Issue by CharlyJazz** [learn-co-students/react-rendering-lab-cb-gh-000#9]
When i try run ```npm test``` the output is:
```
ReferenceError: Enzyme is not defined
    at Object.<anonymous> (/home/charlyjazz/Documentos/Javascript/React/learn-co-students/react-rendering-lab-cb-gh-000/test/index-test.js:33:1)
```

Once the Enzyme has been imported correctly, the output is:
```
ReferenceError: Adapter is not defined
    at Object.<anonymous> (/home/carlosesmarico/Documentos/Javascript/React/learn-co-students/react-rendering-lab-cb-gh-000/test/index-test.js:11:33)
```

**Comment by CharlyJazz** [comment]
Pull request: #10
